import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Mags LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className= "antialiased"
      >
        {children}
        <Toaster/>
      </body>
    </html>
    </ClerkProvider>
  );
  
}
